version: 2
updates:
  # Scan the backend for Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Scan the frontend for Flutter dependencies (pub)
  - package-ecosystem: "pub"
    directory: "/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Scan for GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
